### ISSUE TITLE
Add a settings view

### ISSUE THREAD

**Issue by apomalyn** [RoadTripMoustache/kana_to_kanji#30]
As a user, I want to have a section in the application where I can change the application's theme, reminders, etc.

In this section, I want:
- be able to change the theme (dark, system, light)
- an option to see the acknowledgements (packages and licences used): [LicensePage](https://api.flutter.dev/flutter/material/LicensePage-class.html)
- the version of the application
- an option to report a bug/suggest a feature #28 

## What needs to be done

- [x] Update the settings manager to store/get the theme mode #44 
- [x] Update the app to load the theme mode on boot #44 
- [x] Create a settings view which shows: #43 
  - app version
  - license page
  - change theme mode
