### ISSUE TITLE
feat: Inform user of quest update

### ISSUE THREAD

**Issue by apomalyn** [RoadTripMoustache/kana_to_kanji#346]
## Requirements

Update the Quiz recapitulation view to display the updated and completed quest at the end of a quiz

## What needs to be done

Update `QuizRecapitulation` view and view-model to include a *Quest(s) updated* section. It should:

* use the `QuestCard.large` widget
* retrieve the necessary data from the `QuestRepository` 

## Design

[Figma link](https://www.figma.com/design/ynARb6x2tOibdeCCOq7PgH/App?node-id=1062-8387&t=iXXXOVPfsITX2BSx-4)

## Dependencies

Child of #338

Depends on:

* #issue_number

## Dev notes

# Task check list (Remove after completed)

- [X] Priority label added
- [X] Feature label added if task is linked to a feature
- [ ] (optional) platform label added
- [ ] Project linked
- [ ] (optional) Milestone linked
