### ISSUE TITLE
feat: Implement `ProgressIndicatorTheme`

### ISSUE THREAD

**Issue by apomalyn** [RoadTripMoustache/kana_to_kanji#361]
## Requirements

Implement for both brightness the default `ProgressIndicatorTheme` in  `RTMTheme` .

## What needs to be done

Update `RTMTheme.progressIndicatorTheme` for both brightness following the Figma guideline.

⚠️ Do not forget to merge the incoming theme.

## Design

[Figma link for linear](https://www.figma.com/design/vr4GapRfromR8THCW3DgJx/Design-system--Kana-to-Kanji?node-id=313-608&t=eoIR6twADOtnLBfY-4)

[Figma link for circular](https://www.figma.com/design/vr4GapRfromR8THCW3DgJx/Design-system--Kana-to-Kanji?node-id=666-1710&t=eoIR6twADOtnLBfY-4)

## Dependencies

Child of #issue_number

Depends on:

* #issue_number

Parent of:

* #issue_number

## Dev notes

# Task checklist (Remove after completion)

- [ ] Priority label added
- [ ] Feature label added if the task is linked to a feature
- [ ] (optional) platform label added
- [ ] Project linked
- [ ] (optional) Milestone linked
